### ISSUE TITLE
Discord API error

### ISSUE THREAD

**Issue by Falcon911** [GrosTon1/DayZ-BigBrother#1]
Followed the video three times now. Same issue
`PS C:\tools\DayZBigBrother> node bot.js
(node:6636) UnhandledPromiseRejectionWarning: DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\tools\DayZBigBrother\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.
js:79:15)
    at then (C:\tools\DayZBigBrother\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:6636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Falcon911** [comment]
Figured it out.. Bot role needed admin... All good now
