### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Falcon911** [GrosTon1/DayZ-BigBrother#2]
Weird thing.. Was working just fine up to about 3 days ago. Getting error

C:\tools\DayZBigBrother>node bot.js
(node:5756) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed: Embed size exceeds maximum size of 6000
    at item.request.gen.end (C:\tools\DayZBigBrother\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:79:15)
    at then (C:\tools\DayZBigBrother\node_modules\snekfetch\src\index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Falcon911** [comment]
Fixed.. Apparently for some reason the Token on discord got changed.
